### ISSUE TITLE
Build script and make file only work for currently running kernel

### ISSUE THREAD

**Issue by casaper** [TallGuy74/r8125#1]
This is very unfortunate, since I'm running the box headless.

So every kernel upgrade puts me through the hassle to move the Odroid h2+ to some screen and keyboard in order to build the driver.

And I've looked into the makefile and frankly after a bit of fiddling with the build script and make file I did not make out an easy way to get around that limitation myself.

Can you please either help me to get the thing done myself (by tidying up the build script/makefile a little, so that I manage to get around it) or better just provide an optional flag to the build script that lets me chose a different kernel than the currently running one?

TIA.

**Comment by TallGuy74** [comment]
In `src/Makefile change` line 86 to read `BASEDIR ?= /lib/modules/$(shell uname -r)`

Once that is done, compile and install the module by using
```
make -C src/ BASEDIR=/path/to/lib/modules/kernelversion KERNELDIR=/path/to/build/directory all
```
Just using `make -C src/ KERNELDIR=/path/to/build/directory modules` compiles the module, and you would have to copy the module to it's final directory by hand. If that's enough, you don't need to make any other changes.

Please note the driver is included into the mainline kernel starting with kernel 5.4, so if you can use that kernel you shouldn't have to compile it outside of the kernel tree.

**Comment by casaper** [comment]
@TallGuy74 Thx allot! Will do so. 👍

**Comment by casaper** [comment]
Hello

Sorry to come back with this again. The change in the Makefile doesn't seem to work for me, or at least not in the way you said it would.

Bat anyhow, I seem to have a 5.4 kernel running on the thing actually. But that raises another question here:

@TallGuy74 

> Please note the driver is included into the mainline kernel starting with kernel 5.4, so if you can use that kernel you shouldn't have to compile it outside of the kernel tree.

But how come it doesn't seem to be comming with mine?

```
± ls -lah /lib/modules/5.4.0-47-generic/kernel/drivers/net/ethernet/realtek
total 268K
drwxr-xr-x  2 root root 4.0K Sep  8 21:22 .
drwxr-xr-x 61 root root 4.0K Sep  8 21:22 ..
-rw-r--r--  1 root root  48K Sep  4 19:08 8139cp.ko
-rw-r--r--  1 root root  63K Sep  4 19:08 8139too.ko
-rw-r--r--  1 root root  21K Sep  4 19:08 atp.ko
-rw-r--r--  1 root root 123K Sep  4 19:08 r8169.ko
```

I'm running Ubuntu:

```
) cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
```

Any idea why their Kernel 5.4 package doesn't seem to ship with the driver?

Or am I just looking at the wrong directory here?

Also not in the prev. updated version, I installed, but did not boot with. 

The Kernels `5.4.0-26` and `5.4.0-42` I installed the driver with `autobuild.sh` shell script:

```
) ls -lah /lib/modules/5.4.0-[0-9][0-9]-generic/kernel/drivers/net/ethernet/realtek
/lib/modules/5.4.0-26-generic/kernel/drivers/net/ethernet/realtek:
total 196K
drwxr-xr-x 2 root root 4.0K Sep  4 06:59 .
drwxr-xr-x 3 root root 4.0K Sep  4 06:59 ..
-rw-r--r-- 1 root root 188K Jul 25 20:21 r8125.ko

/lib/modules/5.4.0-42-generic/kernel/drivers/net/ethernet/realtek:
total 456K
drwxr-xr-x  2 root root 4.0K Jul 25 20:26 .
drwxr-xr-x 61 root root 4.0K Jul 25 20:14 ..
-rw-r--r--  1 root root  48K Jul  9 23:50 8139cp.ko
-rw-r--r--  1 root root  63K Jul  9 23:50 8139too.ko
-rw-r--r--  1 root root  21K Jul  9 23:50 atp.ko
-rw-r--r--  1 root root 188K Aug 23 13:27 r8125.ko
-rw-r--r--  1 root root 123K Jul  9 23:50 r8169.ko

/lib/modules/5.4.0-45-generic/kernel/drivers/net/ethernet/realtek:
total 268K
drwxr-xr-x  2 root root 4.0K Sep  3 06:50 .
drwxr-xr-x 61 root root 4.0K Sep  3 06:50 ..
-rw-r--r--  1 root root  48K Aug 26 13:15 8139cp.ko
-rw-r--r--  1 root root  63K Aug 26 13:15 8139too.ko
-rw-r--r--  1 root root  21K Aug 26 13:15 atp.ko
-rw-r--r--  1 root root 123K Aug 26 13:15 r8169.ko

/lib/modules/5.4.0-47-generic/kernel/drivers/net/ethernet/realtek:
total 268K
drwxr-xr-x  2 root root 4.0K Sep  8 21:22 .
drwxr-xr-x 61 root root 4.0K Sep  8 21:22 ..
-rw-r--r--  1 root root  48K Sep  4 19:08 8139cp.ko
-rw-r--r--  1 root root  63K Sep  4 19:08 8139too.ko
-rw-r--r--  1 root root  21K Sep  4 19:08 atp.ko
-rw-r--r--  1 root root 123K Sep  4 19:08 r8169.ko
```

**Comment by casaper** [comment]
@TallGuy74 are you sure with 5.4 having the driver in it:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/ethernet/realtek?h=v5.4.63


Because it doesn't seem to be listed there either.


and even in[ Kernel 5.8.x I can't find it](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/ethernet/realtek?h=linux-5.8.y).

**Comment by casaper** [comment]
@TallGuy74 

I think I just found what you're referring to:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/ethernet?h=v5.8.7&id=f1bce4ad2f1cee6759711904b9fffe4a3dd8af87

Seems to be in the 5.8.7 kernel... ¯\＿(ツ)＿/¯

**Comment by TallGuy74** [comment]
It's in kernel 5.4.0 (and some rc's as well:

```
# git show f1bce4ad2f1ce
commit f1bce4ad2f1cee6759711904b9fffe4a3dd8af87
Author: Heiner Kallweit <hkallweit1@gmail.com>
Date:   Wed Aug 28 22:28:03 2019 +0200

    r8169: add support for RTL8125
    
    This adds support for 2.5Gbps chip RTL8125, it's partially based on the
    r8125 vendor driver. Tested with a Delock 89531 PCIe card against a
    Netgear GS110MX Multi-Gig switch. Firmware isn't strictly needed,
    but on some systems there may be compatibility issues w/o firmware.
    Firmware has been submitted to linux-firmware.
    
    Signed-off-by: Heiner Kallweit <hkallweit1@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>
```
```
# git tag --contains f1bce4ad2f1ce
v5.4
v5.4-rc1
v5.4-rc2
v5.4-rc3
v5.4-rc4
v5.4-rc5
v5.4-rc6
v5.4-rc7
v5.4-rc8
v5.5
v5.5-rc1
v5.5-rc2
v5.5-rc3
v5.5-rc4
v5.5-rc5
v5.5-rc6
v5.5-rc7
v5.6
v5.6-rc1
v5.6-rc2
v5.6-rc3
v5.6-rc4
v5.6-rc5
v5.6-rc6
v5.6-rc7
v5.7
v5.7-rc1
v5.7-rc2
v5.7-rc3
v5.7-rc4
v5.7-rc5
v5.7-rc6
v5.7-rc7
v5.8
v5.8-rc1
v5.8-rc2
v5.8-rc3
v5.8-rc4
v5.8-rc5
v5.8-rc6
v5.8-rc7
v5.9-rc1
v5.9-rc2
v5.9-rc3
v5.9-rc4
```

**Comment by casaper** [comment]
@TallGuy74 so r8169 is the new r8125 then? My bad. So that means then I actually would have never had to build the driver from the start then... 🤣. 

Well Sorry to bother you so much with all that then, and thanks for helping. 😀

**Comment by TallGuy74** [comment]
Yup. It should find it automatically if r8169 is compiled as a module.
